# Autor: Rafael Jimenez
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EC2InstanceType:
    Description: Select Instance Type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
  EC2AMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id


Resources:
# Crear grupo de seguridad
    InstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        Tags:
          - Key: Name
            Value: !Join [ '-', [ !Ref AWS::StackName, !Ref AWS::AccountId] ]
        GroupName: WebServerSecurityGroup
        GroupDescription: "Grupo de seguridad interno para la pila ${AWS::StackName}"
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 3306
            ToPort: 3306
            CidrIp: 0.0.0.0/0

# Crear base de datos
#    WordpressDB:
#      Type: AWS::RDS::DBInstance
#      Properties:
#        DBInstanceIdentifier: RafaDatabase
#        DBName: WordpressDatabase
#        AllocatedStorage: 20
#        DBInstanceClass: db.t3.micro
#        Engine: mariadb
#        EngineVersion: "10.6.10"
#        MasterUsername: rafawordpress
#        MasterUserPassword: rafawordpress1234
#        VPCSecurityGroups: 
#          - !GetAtt
#            - InstanceSecurityGroup
#            - GroupId

# Crear instancia de EC2
    WordpressServerRafa:
      Type: AWS::EC2::Instance
      Properties:
        Tags:
          - Key: Name
            Value: !Join [ '-', [ !Ref AWS::StackName, !Ref AWS::AccountId] ]
        ImageId: ami-0889a44b331db0194
        InstanceType: !Ref EC2InstanceType
        IamInstanceProfile: LabInstanceProfile
        SecurityGroupIds:
          - !Ref InstanceSecurityGroup
        KeyName: vockey
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe

             # Install httpd
            sudo dnf update && sudo dnf upgrade -y
            sudo dnf install httpd -y && sudo service httpd start
            sudo systemctl enable httpd

            # Install MySQLServer
            sudo dnf install mariadb105-server -y && sudo service mariadb start
            sudo service mariadb start
            sudo systemctl enable mariadb

            # Install PHP
            sudo dnf install php php-devel -y

            # Create phpinfo file
            echo "<?php phpinfo();?>" | sudo tee /var/www/html/phpinfo.php &>/dev/null


            # Install the other packages for wordpress
            sudo dnf install wget php-mysqlnd php-fpm php-mysqli php-json -y

            # Wordpress tar download
            su ec2-user
            cd /home/ec2-user
            wget https://wordpress.org/latest.tar.gz && tar -xzf latest.tar.gz
            sudo chown ec2-user:ec2-user wordpress

            # Database Configuration
            sudo mysql -u root -p -e "CREATE USER 'wordpressuser'@'localhost' IDENTIFIED BY 'pass1234$';"
            sudo mysql -u root -p -e "CREATE DATABASE wordpressdb;"
            sudo mysql -u root -p -e "GRANT ALL PRIVILEGES ON wordpressdb.* TO wordpressuser@localhost;"
            sudo mysql -u root -p -e "FLUSH PRIVILEGES;"

            # Edit wp-config.php file
            cp wordpress/wp-config-sample.php wordpress/wp-config.php
            cd wordpress
            sed -i 's/database_name_here/wordpressdb/' wp-config.php

            sed -i 's/username_here/wordpressuser/' wp-config.php

            sed -i 's/password_here/pass1234$/' wp-config.php

            #sed -i 's/localhost/direccion del RDS/' wp-config.php


            # Other configurations
            cd /home/ec2-user
            sudo cp -r wordpress/* /var/www/html/

            sudo sed -i '156 s/None/All/' /etc/httpd/conf/httpd.conf

            sudo dnf install php-gd -y

            sudo chown -R apache:apache /var/www

            sudo chmod 2775 /var/www

            sudo service httpd restart

Outputs:
  InstaceId:
    Description: Instance ID
    Value: !Ref WordpressServerRafa
  ServerPublicIP:
    Description: Public URL of the server
    Value: !Sub "http://${WordpressServerRafa.PublicDnsName}:80"
